name: Build and Release skryper

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Generate .spec file
        run: |
          pyinstaller --name skryper --onefile --specpath src --noconfirm src/skryper/main.py
        shell: cmd

      - name: Build executable with PyInstaller
        run: |
          pyinstaller src/skryper.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: skryper-exe
          path: dist/skryper.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: skryper-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: skryper.exe
          tag_name: "v${{ github.run_id }}-${{ github.run_number }}"
          name: "Release ${{ github.run_id }}-${{ github.run_number }}"
          body: "Automated release of skryper version ${{ github.run_id }}-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
