name: Build and Release skryper

on:
  push:
    tags:
      - "v1.0.0"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name skryper --specpath src src/skryper.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: skryper-exe
          path: src/dist/skryper.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: skryper-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: skryper-exe/skryper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        args:
          tag_name: ${{ github.ref_name }} # Use the tag name as the release name
          release_name: "Release ${{ github.ref_name }}" # Provide a clear and descriptive release name
          body: "Automated release of skryper version ${{ github.ref_name }}."
          draft: false
          prerelease: false
