name: Build, Test, and Release Skryper

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest src/tests/

  build:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with timestamp
        shell: pwsh
        run: |
          $currentDate = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          echo "Building Windows Executable..."
          pyinstaller --onefile --name "skryper_$($currentDate)" src/skryper/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: skryper-exe
          path: dist/skryper_*.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: skryper-exe
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: skryper_*.exe
          tag_name: "v${{ github.run_id }}-${{ github.run_number }}"
          name: "Release ${{ github.run_id }}-${{ github.run_number }}"
          body: "Automated release of skryper version ${{ github.run_id }}-${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
