name: Build and Release skryper

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Get current date
        id: get-date
        run: echo "BUILD_DATE=$(date +'%Y_%m_%d')" >> $GITHUB_ENV
        shell: bash

      - name: Generate .spec file
        run: |
          pyinstaller --name skryper_${{ env.BUILD_DATE }} --onefile --specpath src --noconfirm src/main.py
        shell: cmd

      - name: Build executable with PyInstaller
        run: |
          pyinstaller src/skryper_${{ env.BUILD_DATE }}.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: skryper-exe
          path: dist/skryper_${{ env.BUILD_DATE }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: skryper-exe

      - name: Get current date
        id: date
        run: echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: skryper_${{ env.BUILD_DATE }}.exe
          tag_name: "v1.0-${{ env.RELEASE_DATE }}"
          name: "Release v1.0 - ${{ env.RELEASE_DATE }}"
          body: "Automated release of skryper on ${{ env.RELEASE_DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
